# Generated by Django 3.2.8 on 2021-10-07 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinformation',
            name='inn',
            field=models.CharField(max_length=10, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='additionaluserinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
    ]
